//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOrderTwoGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Productos = new HashSet<Productos>();
            this.Usuarios = new HashSet<Usuarios>();
            this.Carrito = new HashSet<Carrito>();
        }
        public Empresa(DataRow r)
        {
            idEmpresa = Convert.ToInt32(r["idEmpresa"]);
            nameEmpresa = Convert.ToString(r["nameEmpresa"]);
            DescripcionEmpresa = Convert.ToString(r["DescripcionEmpresa"]);
            numeroTelefono = Convert.ToInt32(r["numeroTelefono"]);

        }

        public int idEmpresa { get; set; }
        public string nameEmpresa { get; set; }
        public string DescripcionEmpresa { get; set; }
        public Nullable<int> numeroTelefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
    }
}
