//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOrderTwoGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Productos
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Carrito = new HashSet<Carrito>();
        }

        public int idProduct { get; set; }
        [Required]
        [DisplayName("Nombre del Producto:")]
        public string ProductNam { get; set; }
        [Required]
        [DisplayName("Empresa:")]
        public Nullable<int> idEmpresa { get; set; }
        [Required]
        [DisplayName("Precio")]
        public Nullable<int> precio { get; set; }
        [Required]
        [DisplayName("Cantidad de Productos:")]
        public Nullable<int> stock { get; set; }
        public string ImagenProducto { get; set; }

        public virtual Empresa Empresa { get; set; }

        public HttpPostedFileBase Imagen { get; set; }

        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
    }
}
