//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOrderTwoGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class Roles
    {
        public int idRol { get; set; }
        public string nameRol { get; set; }

        public Roles(DataRow r)
        {
            idRol = Convert.ToInt32(r["idRol"]);
            nameRol = Convert.ToString(r["nameRol"]);
        }
    }
}
